### ISSUE TITLE
Incorrect CST for prefix operation at LHS of infix operation

### ISSUE THREAD

**Issue by Johan-Mi** [Johan-Mi/b#12]
Minimal example:
```c
f() {
   ++a + b;
}
```

Resulting CST:
```yaml
start node: document
  start node: function
    token: identifier
    start node: function_parameters
      token: (
      token: )
      finish node
    token: trivia
    start node: compound_statement
      token: {
      token: trivia
      start node: expression_statement
        checkpoint
        start node: prefix_operation
          token: ++
          checkpoint
          start node: variable
            token: identifier
            finish node
          finish node
        finish node
      token: trivia
      start node: expression_statement
        checkpoint
        start node: error
          token: +
          finish node
        finish node
      token: trivia
      start node: expression_statement
        checkpoint
        start node: variable
          token: identifier
          finish node
        token: ;
        finish node
      token: trivia
      token: }
      finish node
    finish node
  finish node
```

The parser appears to give up before consuming the `+` operator.
